version: '3.8'

services:
    app:
        container_name: api
        build:
            context: .
            dockerfile: Dockerfile
            args:
                - PORT=${PORT}
        depends_on:
            - mongodb
        restart: unless-stopped
        env_file: .env
        ports:
            - ${PORT}:${PORT}
        environment:
            - TOKEN=${TOKEN}
            - PORT=${PORT}
            - MONGODB_ENABLED=${MONGODB_ENABLED}
            - MONGODB_URL=mongodb+srv://miguelrosa81:rqZdsYtVo4LUWndf@linkf5.tkueohe.mongodb.net/?retryWrites=true&w=majority
            - WEBHOOK_ENABLED=${WEBHOOK_ENABLED}
            - WEBHOOK_URL=${WEBHOOK_URL}
            - WEBHOOK_BASE64=${WEBHOOK_BASE64}
        volumes:
            - ./:/home/node/app
            - /home/node/app/node_modules/